//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RusadaWebAPIProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AircraftSighting
    {
        public int SightingId { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string Registration { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> Date_and_Time { get; set; }
        public string photo { get; set; }
    }
}
